name: Push to Registries

on:
  push:
    tags: ['*']

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile.ffmpeg-frozen   
            suffix: ''
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository_owner }}/${{ github.event.repository.name }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          tags: |
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ matrix.suffix != '' && format('{0}-{1}', matrix.suffix, steps.meta.outputs.version) || steps.meta.outputs.version }}
            ${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ matrix.suffix != '' && format('{0}-{1}', matrix.suffix, steps.meta.outputs.version) || steps.meta.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}${{ matrix.suffix != '' && format(':{0}', matrix.suffix) || '' }}
            ${{ github.repository_owner }}/${{ github.event.repository.name }}${{ matrix.suffix != '' && format(':{0}', matrix.suffix) || '' }}